name: Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

env:
  JAVA_VERSION: '21'
  MAVEN_OPTS: >-
    -Xmx2g
    -XX:+UseG1GC
    -Dmaven.repo.local=${{ github.workspace }}/.m2/repository

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            TAG="v${VERSION}"
          else
            TAG="${GITHUB_REF#refs/tags/}"
            VERSION="${TAG#v}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Release version: ${VERSION}"
          echo "Release tag: ${TAG}"

      - name: Validate version format
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if ! [[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$ ]]; then
            echo "Invalid version format: ${VERSION}"
            echo "Expected format: X.Y.Z or X.Y.Z-qualifier"
            exit 1
          fi

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    needs: prepare-release
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update version in POM
        run: |
          ./mvnw versions:set -DnewVersion=${{ needs.prepare-release.outputs.version }} --batch-mode
          ./mvnw versions:commit --batch-mode

      - name: Build and test
        run: ./mvnw clean verify --batch-mode --errors

      - name: Build release artifacts
        run: ./mvnw clean package -DskipTests --batch-mode

      - name: Build source and javadoc JARs
        run: |
          ./mvnw source:jar javadoc:jar --batch-mode

      - name: Sign artifacts
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./mvnw gpg:sign --batch-mode
        continue-on-error: true

      - name: Create distribution
        run: |
          mkdir -p release
          find . -type f \( -name '*.jar' -o -name '*.pom' \) \
            -not -path '*/target/*-tests.jar' \
            -not -path '*/.m2/*' \
            -exec cp {} release/ \;

          cd release
          tar -czf cheshire-${{ needs.prepare-release.outputs.version }}.tar.gz *.jar
          zip -r cheshire-${{ needs.prepare-release.outputs.version }}.zip *.jar

          # Create checksums
          sha256sum * > checksums.txt

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            release/*.jar
            release/*.tar.gz
            release/*.zip
            release/checksums.txt
          retention-days: 90

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ prepare-release, build-release ]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: release

      - name: Generate release notes
        id: release_notes
        run: |
          # Extract changelog for this version
          VERSION="${{ needs.prepare-release.outputs.version }}"

          # Generate release notes from git log
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -n "$PREVIOUS_TAG" ]; then
            echo "## What's Changed" > release_notes.md
            git log ${PREVIOUS_TAG}..HEAD --pretty=format:"- %s (%h)" >> release_notes.md
          else
            echo "## Initial Release" > release_notes.md
            echo "First release of Cheshire Framework" >> release_notes.md
          fi

          echo "" >> release_notes.md
          echo "## Artifacts" >> release_notes.md
          echo "- \`cheshire-${VERSION}.tar.gz\` - Distribution archive (tar.gz)" >> release_notes.md
          echo "- \`cheshire-${VERSION}.zip\` - Distribution archive (zip)" >> release_notes.md
          echo "- Individual JAR files for each module" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare-release.outputs.tag }}
          name: Release ${{ needs.prepare-release.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(needs.prepare-release.outputs.version, '-') }}
          files: |
            release/*.tar.gz
            release/*.zip
            release/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-maven-central:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs: [ prepare-release, build-release ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Update version
        run: |
          ./mvnw versions:set -DnewVersion=${{ needs.prepare-release.outputs.version }} --batch-mode
          ./mvnw versions:commit --batch-mode

      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./mvnw clean deploy -P release --batch-mode
        continue-on-error: true

  publish-docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [ prepare-release, build-release ]
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/cheshire
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.prepare-release.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.prepare-release.outputs.version }}
            type=semver,pattern={{major}},value=${{ needs.prepare-release.outputs.version }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.prepare-release.outputs.version }}

  notify-release:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [ prepare-release, create-github-release ]
    if: always()

    steps:
      - name: Send notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "🚀 New release: Cheshire ${{ needs.prepare-release.outputs.version }}",
              attachments: [{
                color: 'good',
                text: `Release ${{ needs.prepare-release.outputs.tag }} has been published\nhttps://github.com/${{ github.repository }}/releases/tag/${{ needs.prepare-release.outputs.tag }}`
              }]
            }
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true

